version: 2.1

jobs:
  test:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests

orbs:
  node: circleci/node@4.0.0
  
workflows:
  test:
    jobs:
      - test
